[package]
name = "clsag_vs_fcmppp_bench"
version = "0.1.0"
edition = "2021"

[dependencies]
monero-fcmp-plus-plus = { path = "monero-oxide/monero-oxide/ringct/fcmp++", default-features = false, features = ["std"]}
#fcmps = { package = "full-chain-membership-proofs", path = "fcmp-plus-plus/crypto/fcmps", default-features = false }
#std-shims = { path = "../../common/std-shims", version = "^0.1.1", default-features = false }

rand_core = { version = "0.6", default-features = false }

#zeroize = { version = "^1.5", default-features = false, features = ["zeroize_derive"] }

generic-array = { version = "1", default-features = false, features = ["alloc"] }

blake2 = { version = "0.10", default-features = false }

multiexp = { version = "0.4", default-features = false }
curve25519-dalek = { version = "4", default-features = false, features = ["alloc", "zeroize"] }
dalek-ff-group = { version = "0.4", default-features = false }
helioselene = { path = "monero-oxide/crypto/helioselene", default-features = false }
ciphersuite = { version = "0.4", default-features = false, features = ["ed25519"] }


generalized-bulletproofs = { path = "monero-oxide/crypto/generalized-bulletproofs", default-features = false }
ec-divisors = { path = "monero-oxide/crypto/divisors", default-features = false, features = ["ed25519"] }
generalized-bulletproofs-ec-gadgets = { path = "monero-oxide/crypto/fcmps/ec-gadgets", default-features = false }
fcmps = { package = "full-chain-membership-proofs", path = "monero-oxide/crypto/fcmps", default-features = false }

monero-generators = { path = "monero-oxide/monero-oxide/generators", default-features = false }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[build-dependencies]
cmake = "0.1"

[[bench]]
name = "benchmark"
harness = false

